CREATE DATABASE NoticiasGeek;

USE NoticiasGeek;

CREATE TABLE Usuario (
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(45),
Email VARCHAR(45) UNIQUE,
Senha VARCHAR(20)
)AUTO_INCREMENT 1000;

CREATE TABLE Canal (
idCanal INT PRIMARY KEY AUTO_INCREMENT,
NomaCanal VARCHAR(45)
) AUTO_INCREMENT =100;

CREATE TABLE Descricao (
idDescricao INT PRIMARY KEY AUTO_INCREMENT,
descricao TEXT,
fkCanal INT,
CONSTRAINT FKCANAL_DESCRITIVO FOREIGN KEY (fkCanal) 
REFERENCES Canal (idCanal)
) AUTO_INCREMENT =200;

CREATE TABLE Video (
idVideo INT PRIMARY KEY AUTO_INCREMENT,
fkCanal_video INT,
CONSTRAINT FKCANAL FOREIGN KEY (fkCanal_video) 
REFERENCES Canal (idCanal),
Raking INT,
Titulo VARCHAR(45),
Link VARCHAR (150)
);

-- 1 - N --



DROP DATABASE NoticiasGeek;

DROP TABLE Descricao;

